In [1]:
import sys
sys.path.insert(0, '../')
%load_ext autoreload
%autoreload 2
from cross_validation import cross_validation, cross_validation_np
import numpy as np

In [2]:
np.random.seed(42)
data_np = np.random.rand(5, 2)
data_np

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [3]:
data = data_np.tolist()
data

[[0.3745401188473625, 0.9507143064099162],
 [0.7319939418114051, 0.5986584841970366],
 [0.15601864044243652, 0.15599452033620265],
 [0.05808361216819946, 0.8661761457749352],
 [0.6011150117432088, 0.7080725777960455]]

# No NumPy

In [5]:
k = 3
folds = cross_validation(k, data, validation=True)

In [9]:
folds[0][0]

[2, 3, 4]

In [10]:
for fold_idx in range(k):
    print("\nfold ", fold_idx)
    print("train:")
    for idx in folds[fold_idx][0]:
        print(data[idx])
    print("validation:")
    for idx in folds[fold_idx][1]:
        print(data[idx])
    print("test:")
    for idx in folds[fold_idx][2]:
        print(data[idx])


fold  0
train:
[0.15601864044243652, 0.15599452033620265]
[0.05808361216819946, 0.8661761457749352]
[0.6011150117432088, 0.7080725777960455]
validation:
[0.3745401188473625, 0.9507143064099162]
test:
[0.7319939418114051, 0.5986584841970366]

fold  1
train:
[0.3745401188473625, 0.9507143064099162]
[0.05808361216819946, 0.8661761457749352]
[0.6011150117432088, 0.7080725777960455]
validation:
[0.7319939418114051, 0.5986584841970366]
test:
[0.15601864044243652, 0.15599452033620265]

fold  2
train:
[0.3745401188473625, 0.9507143064099162]
[0.7319939418114051, 0.5986584841970366]
[0.6011150117432088, 0.7080725777960455]
validation:
[0.15601864044243652, 0.15599452033620265]
test:
[0.05808361216819946, 0.8661761457749352]


# NumPy

In [12]:
def cross_validation_np(k, data, validation = False):
    n_sample, n_feature = data.shape
    n_sample_fold = n_sample // k
    indicies = list(range(n_sample))
    idx_folds = []
    for fold in range(k):
        if validation:
            assert k > 2, print("not enough folds!")
            val_idx = indicies[fold * n_sample_fold:(fold + 1) * n_sample_fold]
            test_idx = indicies[(fold + 1) * n_sample_fold:(fold + 2) * n_sample_fold]

            train_idx_part_1 = indicies[:fold * n_sample_fold]
            train_idx_part_2 = indicies[(fold + 2) * n_sample_fold:]
            train_idx = train_idx_part_1 + train_idx_part_2

            idx_folds.append([train_idx, val_idx, test_idx])
        else:
            test_idx = indicies[fold * n_sample_fold:(fold + 1) * n_sample_fold]

            train_idx_part_1 = indicies[:fold * n_sample_fold]
            train_idx_part_2 = indicies[(fold + 1) * n_sample_fold:]
            train_idx = np.concatenate([train_idx_part_1, train_idx_part_2])

            idx_folds.append([train_idx, test_idx])
    return idx_folds

In [14]:
k = 3
folds_np = cross_validation_np(k, data_np, validation=True)

In [15]:
folds_np

[[[2, 3, 4], [0], [1]], [[0, 3, 4], [1], [2]], [[0, 1, 4], [2], [3]]]

In [17]:
for fold_idx in range(k):
    print("\nfold ", fold_idx)
    print("train:")
    print(data_np[folds[fold_idx][0]])
    print("validation:")
    print(data_np[folds[fold_idx][1]])
    print("test:")
    print(data_np[folds[fold_idx][2]])


fold  0
train:
[[0.15601864 0.15599452]
 [0.05808361 0.86617615]
 [0.60111501 0.70807258]]
validation:
[[0.37454012 0.95071431]]
test:
[[0.73199394 0.59865848]]

fold  1
train:
[[0.37454012 0.95071431]
 [0.05808361 0.86617615]
 [0.60111501 0.70807258]]
validation:
[[0.73199394 0.59865848]]
test:
[[0.15601864 0.15599452]]

fold  2
train:
[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.60111501 0.70807258]]
validation:
[[0.15601864 0.15599452]]
test:
[[0.05808361 0.86617615]]
